### ISSUE TITLE
Crash when exporting RE6 SPCs

### ISSUE THREAD

**Issue by Roachisserie** [LuBuCake/MTF.SoundTool#2]
# Steps to reproduce
1. Import any RE6 SPC
2. Export (as WAVE)
3. Close
4. Import another SPC
5. Export (as WAVE)
6. Click the close button

I get this exception and the list does not clear, and importing anything after this is another exception
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MTF.SoundTool.App.CloseSPACFile_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at DevExpress.XtraEditors.BaseButton.OnClick(EventArgs e)
   at DevExpress.XtraEditors.BaseButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.Utils.Controls.ControlBase.BaseWndProc(Message& m)
   at DevExpress.Utils.Controls.ControlBase.WndProc(Message& m)
   at DevExpress.XtraEditors.BaseControl.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
MTFSoundTool
    Assembly Version: 1.0.0.2
    Win32 Version: 1.0.0.2
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Resident%20Evil%20Biohazard%20HD%20REMASTER/nativePC/ARCtool/MTFSoundTool/MTFSoundTool.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
DevExpress.Utils.v21.1
    Assembly Version: 21.1.3.0
    Win32 Version: 21.1.3.0
    CodeBase: file:///C:/Users/roach/AppData/Local/Temp/Costura/5A3C33596D0C36C59CEA853BB84E52BA/devexpress.utils.v21.1.dll
----------------------------------------
DevExpress.Data.v21.1
    Assembly Version: 21.1.3.0
    Win32 Version: 21.1.3.0
    CodeBase: file:///C:/Users/roach/AppData/Local/Temp/Costura/5A3C33596D0C36C59CEA853BB84E52BA/devexpress.data.v21.1.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
DevExpress.Data.Desktop.v21.1
    Assembly Version: 21.1.3.0
    Win32 Version: 21.1.3.0
    CodeBase: file:///C:/Users/roach/AppData/Local/Temp/Costura/5A3C33596D0C36C59CEA853BB84E52BA/devexpress.data.desktop.v21.1.dll
----------------------------------------
DevExpress.XtraEditors.v21.1
    Assembly Version: 21.1.3.0
    Win32 Version: 21.1.3.0
    CodeBase: file:///C:/Users/roach/AppData/Local/Temp/Costura/5A3C33596D0C36C59CEA853BB84E52BA/devexpress.xtraeditors.v21.1.dll
----------------------------------------
DevExpress.XtraGrid.v21.1
    Assembly Version: 21.1.3.0
    Win32 Version: 21.1.3.0
    CodeBase: file:///C:/Users/roach/AppData/Local/Temp/Costura/5A3C33596D0C36C59CEA853BB84E52BA/devexpress.xtragrid.v21.1.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
DevExpress.XtraLayout.v21.1
    Assembly Version: 21.1.3.0
    Win32 Version: 21.1.3.0
    CodeBase: file:///C:/Users/roach/AppData/Local/Temp/Costura/5A3C33596D0C36C59CEA853BB84E52BA/devexpress.xtralayout.v21.1.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Data.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Linq.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///C:/Users/roach/AppData/Local/Temp/Costura/5A3C33596D0C36C59CEA853BB84E52BA/newtonsoft.json.dll
----------------------------------------
UIAutomationClient
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationClient/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationClient.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
Updater
    Assembly Version: 1.0.0.1
    Win32 Version: 1.0.0.2
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Resident%20Evil%20Biohazard%20HD%20REMASTER/nativePC/ARCtool/MTFSoundTool/MTFSoundTool.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by LuBuCake** [comment]
Thanks for pointing it out! Issue fixed and app updated.
